import type { Metadata } from "next";
import { Source_Serif_4 } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";

const font = Source_Serif_4({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Hernán Arévalo | Frontend Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.className}>

      <body className='bg-negro text-blanco relative min-h-screen'>
        {children}

        <Navbar />
      </body>
    </html>
  );
}
